name: mautic
type: php
docroot: ""
php_version: "8.1"
webserver_type: apache-fpm
router_http_port: "80"
router_https_port: "443"
xdebug_enabled: false
additional_hostnames: []
additional_fqdns: []
mariadb_version: "10.3"
mysql_version: ""
provider: default
use_dns_when_possible: true
composer_version: "2"
webimage_extra_packages: [php8.1-imap]
hooks:
  post-start:
    # Fix line endings on Windows
    - exec: sed -i -e 's/\r$//' ./.ddev/mautic-setup.sh
    - exec: sed -i -e 's/\r$//' ./.git/hooks/*
    - exec: "yes | ./.ddev/mautic-setup.sh"
