name: 'Split up the monorepo into subrepositories for composer purposes'

on:
    push:
        # Only trigger for specific branches or changes in specific paths.
        branches:
            - '[0-9].*'
            - 'gitsplit-action-debug'
        paths:
            - app/**
            - plugins/**
            - themes/**
            # also run when actions are being modified for testing purposes.
            - .github/** 
        # Tag push events should be ignored, they will be handled with the create event below.
        tags-ignore:
            - '*'
    create:
        tags:
            - '*'
        branches:
            - '[0-9].*'
            - 'gitsplit-action-debug'
    delete:
        tags:
            - '*'
        branches:
            - '[0-9].*'
            - 'gitsplit-action-debug'

jobs:
    sync:
        if: github.repository_owner == 'mautic'
        runs-on: ubuntu-latest
        name: Sync commits into separate repos
        steps:
            -   uses: actions/checkout@v2
                with:
                    persist-credentials: false
                    fetch-depth: 0

            # Add a personal access token to the repository secrets. This will allow the splitter action to push the new commits
            -   uses: frankdejonge/use-github-token@1.0.1
                with:
                    authentication: 'username:${{ secrets.ACCESS_TOKEN }}'
                    user_name: 'Mautic CI'
                    user_email: 'ci@mautic.org'

            # Sync commits and tags for the configured subtree splits
            -   name: subtree split
                uses: acrobat/subtree-splitter@main
                with:
                    config-path: .github/subtree-splitter-config.json
